[package]
name = "slack-stream-json"
version = "0.1.0"
authors = ["motemen <motemen@gmail.com>"]

[dependencies]
structopt = "0.3"
reqwest = "0.9"
url = "2.0"
tungstenite = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["raw_value"] }
